services:
  mcp:
    restart: always
    build:
      context: .
      dockerfile: mcp/Dockerfile
    container_name: mcp
    volumes:
      - mcp_app_data:/home/quart/instance/apps

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - mcp

volumes:
  mcp_app_data:
    external: true
  caddy_data:
    external: true
  caddy_config:
    external: true