services:
  omadamcp:
    restart: always
    build:
      context: .
      dockerfile: omadamcp/Dockerfile
    container_name: omadamcp
    volumes:
      - omada_mcp_data:/home/quart/instance/apps

  ubntmcp:
    restart: always
    build:
      context: .
      dockerfile: ubntmcp/Dockerfile
    container_name: ubntmcp
    volumes:
      - ubnt_mcp_data:/home/quart/instance/apps

  proxymcp:
    restart: always
    build:
      context: .
      dockerfile: proxymcp/Dockerfile
    container_name: proxymcp
    volumes:
      - proxy_mcp_data:/home/quart/instance/apps

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - proxymcp
      - ubntmcp
      - omadamcp

volumes:
  proxy_mcp_data:
    external: true
  ubnt_mcp_data:
    external: true
  omada_mcp_data:
    external: true
  caddy_data:
    external: true
  caddy_config:
    external: true